### ISSUE TITLE
Jumpsuits occasionally disappear outright.

### ISSUE THREAD

**Issue by unit0016** [StarbloomSS13/StarbloomSS13#166]
Doing something to update the icon will make it reappear, however.

**Comment by distributivgesetz** [comment]
reproduction please

**Comment by unit0016** [comment]
> reproduction please

Be digitigrade lizard.
Just exist for 15 minutes. Jumpsuit will disappear.

It *really* is that simple.

**Comment by Justice12354** [comment]
> > reproduction please
> 
> Be digitigrade lizard. Just exist for 15 minutes. Jumpsuit will disappear.
> 
> It _really_ is that simple.

This is the one of the oldest bug in the book of ss13 bugs
