### ISSUE TITLE
Digitigrade Legs. Just in general.

### ISSUE THREAD

**Issue by unit0016** [StarbloomSS13/StarbloomSS13#167]
When digi legs are meant to jump to their fallback plantigrade icons from how /tg/ does it, they turn invisible entirely.

**Comment by distributivgesetz** [comment]
reproduction? related to modsuits?

**Comment by unit0016** [comment]
> reproduction? related to modsuits or something different entirely?

Wear anything that covers your legs codewise. Jumpsuit, detective jacket, tactical skirtleneck. *Anything.*
